version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-action"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yyamaurffvm2"
s3_prefix = "test-action"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
confirm_changeset = true
