AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-action

  Sample SAM Template for test-action

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./test
      Handler: test.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get
         ScheduledFunction:
           Type: Schedule
           Properties:
             Schedule: cron(25 16 * * ? *)

  HelloWorldFunction2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serve>
    Properties:
      CodeUri: ./test
      Handler: test.lambda2
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-applicatio>
#          Properties:
#            Path: /hello
#            Method: get
         ScheduledFunction:
           Type: Schedule
           Properties:
             Schedule: cron(30 12 * * ? *)
