name: test
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
     # - name: Install dependencies
     #   run: |
     #     ls -la
     #     ls .aws-sam/build/HelloWorldFunction/
      

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name test-action --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-yyamaurffvm2
