on:
  push:
    branches:
      - test
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - uses: aws-actions/setup-sam@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build 
      - name: Install dependencies
        run: |
          ls -la
          ls .aws-sam/build/HelloWorldFunction/
      #--use-container --debug --template-file ./template.yaml

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name test-action --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-yyamaurffvm2
